name: turing_academy
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  get_it: ^4.0.0
  flutter_swiper: ^1.1.6
  page_transition: ^1.1.5
  pin_code_fields: ^2.5.1
  flutter_money_formatter: ^0.8.3
  flutter_statusbarcolor: ^0.2.3
  http: ^0.12.2
  introduction_screen: ^1.0.8
  chewie: ^0.9.10
  cached_network_image: ^2.1.0+1
  toast: ^0.1.5
  razorpay_flutter: 1.1.3
  shared_preferences: ^0.5.7+1
  intl: ^0.15.8
  flutter_slidable: ^0.5.4
  flutter_youtube: ^2.0.0
  flutter_inappwebview: ^3.2.0
#  used for play youtube video
#  youtube_player_flutter: ^6.1.1
  image_picker: ^0.6.6+1
  path: ^1.6.4
  flutter_local_notifications: ^1.4.2
  firebase_messaging: ^6.0.13
  flutter_masked_text: ^0.8.0
  location: ^3.0.2
  geocoder: ^0.2.1
  country_code_picker: ^1.3.12+1
  email_validator: '^1.0.0'
  image_cropper: ^1.2.2
  sms_autofill: ^1.2.1
  url_launcher: ^5.5.0
  flutter_html: ^1.0.2

#  flutter_html:
#    path: ./flutter_html-master



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_Icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/tutorials_1.png
    - assets/tutorials_2.png
    - assets/tutorials_3.png
    - assets/tutorials_4.png
    - assets/top_bg.png
    - assets/bottom_bg.png
    - assets/menu-icon.png
    - assets/cart-icon.png
    - assets/back-arrow.png
    - assets/wishlist.png
    - assets/course-bottom-tab.png
    - assets/product-bottom-tab.png
    - assets/notification-bottom-tab.png
    - assets/user.png
    - assets/01_home.png
    - assets/02_my_kids.png
    - assets/04_product.png
    - assets/03_coures.png
    - assets/04_product.png
    - assets/03_coures.png
    - assets/04_product.png
    - assets/05_active_service.png
    - assets/06_order_history.png
    - assets/07_Notification.png
    - assets/08_profile.png
    - assets/09_address.png
    - assets/10_logout.png
    - assets/notification-icon.png
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Montserrat
     fonts:
       - asset: assets/fonts/montserrat/Montserrat-Light.ttf
         weight: 200
       - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
       - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
         weight: 600  
